version: "3"

includes:
  tauri:
    taskfile: ../../taskfiles/tauri.yml
    flatten: true
    vars:
      ARTIFACT_NAME: "desktop"
  rust:
    taskfile: ../../taskfiles/rust.yml
    dir: src-tauri
  typescript: ../../taskfiles/typescript.yml

tasks:

  dev:
    desc: Run the app in development mode
    cmds:
      - pnpm tauri dev

  check:
    desc: Run all checks
    deps: [rust:check, typescript:check]
